# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x07gateway\"E\n\x06\x43onfig\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x13\n\x0b\x65nable_wifi\x18\x03 \x01(\x08\"2\n\x0cLightCommand\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07turn_on\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty\"*\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"[\n\x0c\x44\x65viceStatus\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06uptime\x18\x02 \x01(\t\x12\x10\n\x08light_on\x18\x03 \x01(\x08\x12\x16\n\x0ewifi_connected\x18\x04 \x01(\x08\"\\\n\rTelemetryData\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x05\x12\x10\n\x08humidity\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x32\xe0\x01\n\x07Gateway\x12-\n\tSetConfig\x12\x0f.gateway.Config\x1a\x0f.gateway.Status\x12\x32\n\tGetStatus\x12\x0e.gateway.Empty\x1a\x15.gateway.DeviceStatus\x12\x35\n\x0bTurnOnLight\x12\x15.gateway.LightCommand\x1a\x0f.gateway.Status\x12;\n\x0fStreamTelemetry\x12\x0e.gateway.Empty\x1a\x16.gateway.TelemetryData0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIG']._serialized_start=26
  _globals['_CONFIG']._serialized_end=95
  _globals['_LIGHTCOMMAND']._serialized_start=97
  _globals['_LIGHTCOMMAND']._serialized_end=147
  _globals['_EMPTY']._serialized_start=149
  _globals['_EMPTY']._serialized_end=156
  _globals['_STATUS']._serialized_start=158
  _globals['_STATUS']._serialized_end=200
  _globals['_DEVICESTATUS']._serialized_start=202
  _globals['_DEVICESTATUS']._serialized_end=293
  _globals['_TELEMETRYDATA']._serialized_start=295
  _globals['_TELEMETRYDATA']._serialized_end=387
  _globals['_GATEWAY']._serialized_start=390
  _globals['_GATEWAY']._serialized_end=614
# @@protoc_insertion_point(module_scope)
